version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongoData:/var/backups

  web:
    image: sample2:7
    ports:
      - 8833:8833
    depends_on:
      - mongodb

volumes:
  mongoData:
